# Generated by Django 2.2.1 on 2020-05-19 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voteapp', '0002_award_artistnum'),
    ]

    operations = [
        migrations.CreateModel(
            name='Triva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.CharField(max_length=500)),
            ],
        ),
    ]
