# Generated by Django 4.1.5 on 2023-02-15 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voteapp', '0003_triva'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voted',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userVoted', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
